package api.notifii.notifiiv20apis.sendgrid.apipageclasses; 

public class SendGridEmailDataset{

public static final int datasetLength = 1; 

public static String projectName = "notifii";

			/*--------Dataset# Valid Details Dataset-----------*/

public static final String datasetHeader1 = "TC_SendEmail-Dataset# Valid Details";

public static final String datasetResources1 = "session/sendEmail";
public static final int requestType1 = 2;
public static final int bodyType1 = 3;
public static final String apiName1 = "Send Grid- Email";

 public static String urlParams1  = "[]";

 public static String headers1  = "[]";

public static final String authenticationData1 = "{\"authtype\":\"noauth\","
 + "\"basicauth\":{\"username\":\"\","
 + "\"password\":\"\"},"
 + "\"apikey\":{\"key\":\"\","
 + "\"value\":\"\","
 + "\"addto\":\"header\"},"
 + "\"bearertoken\":{\"token\":\"\"}}";


 public static String body1  = "{\"raw_text\":\"{\\n    \\\"toEmails\\\": [\\n        \\\"kvraghav444@gmail.com\\\","
 + "\\n        \\\"raghavendra.kudumula@devrabbit.com\\\"\\n    ],"
 + "\\n    \\\"substitutions\\\": {},"
 + "\\n    \\\"placeholders\\\":{\\n    \\t\\\"first_name\\\":\\\"Raghava\\\","
 + "\\n    \\t\\\"last_name\\\":\\\"Vijay\\\","
 + "\\n    \\t\\\"address1\\\":\\\"Hyderabad\\\"\\n    },"
 + "\\n    \\\"fromEmails\\\": {\\n        \\\"email\\\": \\\"dev@yopmail.com\\\","
 + "\\n        \\\"name\\\": \\\"Notifii Apartment\\\"\\n    },"
 + "\\n    \\\"ccEmails\\\": [\\n        {\\n            \\\"email\\\": \\\"devcc@yopmail.com\\\","
 + "\\n            \\\"name\\\": \\\"Notifii Apartment\\\"\\n        },"
 + "\\n        {\\n            \\\"email\\\": \\\"devcc1@yopmail.com\\\","
 + "\\n            \\\"name\\\": \\\"Notifii Apartment1\\\"\\n        }\\n    ],"
 + "\\n    \\\"bccEmails\\\": [\\n        {\\n            \\\"email\\\": \\\"devbcc@yopmail.com\\\","
 + "\\n            \\\"name\\\": \\\"Notifii Apartment\\\"\\n        },"
 + "\\n        {\\n            \\\"email\\\": \\\"devbcc1@yopmail.com\\\","
 + "\\n            \\\"name\\\": \\\"Notifii Apartment\\\"\\n        }\\n    ],"
 + "\\n    \\\"bccSubject\\\": \\\"[BCC] Corporate-Test Template with All Fonts\\\","
 + "\\n    \\\"replyToEmails\\\": {\\n        \\\"email\\\": \\\"test@yopmail.com\\\"\\n    },"
 + "\\n    \\\"subject\\\": \\\"Notifii Apartment\\\","
 + "\\n    \\\"attachments\\\": [\\n        \\\"https://www.devrabbit.com/wp-content/uploads/2016/04/logo21.png\\\","
 + "\\n        \\\"https://s3-us-west-1.amazonaws.com/suiteam-website/Website-Images/SA-Logo.png\\\"\\n    ],"
 + "\\n    \\\"customArgs\\\":{\\n    \\t\\\"primaryId\\\":\\\"12345678\\\"\\n    },"
 + "\\n    \\\"sendType\\\": \\\"GENERAL\\\","
 + "\\n    \\\"emailBody\\\": \\\"Hi [FULL NAME],"
 + " <br/> Address:[ADDRESS1],"
 + " <br/><table align='center' border='1' cellpadding='20' style='border: 1px solid rgb(89,"
 + " 89,"
 + " 89); border-image: none; width: 600px;'><tbody><tr><td><p><img alt='' border='0' height='270' hspace='0' src='https://s3.amazonaws.com/notifii-user-content-111/custom-message-attachments/10134_corp_170906132211_4964346.jpeg' style='margin: 0px; border: 0px solid black; border-image: none; width: 600px; height: 270px;' vspace='0' width='600' /><\\/p><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><span style='font-family: Arial,"
 + "Helvetica,"
 + "sans-serif;'>Hello Residents,"
 + "<\\/span><br /><br />With Hurricane Irma projected to hit Florida later this week,"
 + " we are getting our community ready for the storm,"
 + " and we want to make sure you&rsquo;re prepared to weather the storm too! Here are a few reminders on steps to take now and what to do before,"
 + " during,"
 + " and after a hurricane. There is a lot of information to share,"
 + " so <strong>please read to the end<\\/strong>.<\\/span><br /><br /><span style='color: rgb(0,"
 + " 133,"
 + " 202);'><strong>KEY EMERGENCY CONTACTS<\\/strong><\\/span><br /><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>It&rsquo;s important to stay up-to-date on the latest information and weather reports. Here are some key resources to keep handy.<\\/span><\\/span><\\/p><p style='text-align: left; margin-left: 40px;'><span style='font-size: 14px;'><span style='color: rgb(0,"
 + " 133,"
 + " 202);'><strong>Florida Emergency Information Line<\\/strong><\\/span>: <span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>1-800-342-3557<\\/strong><\\/span><\\/span><\\/p><p style='text-align: left; margin-left: 40px;'><span style='font-size: 14px;'><span style='color: rgb(0,"
 + " 133,"
 + " 202);'><strong>Information on Evacuation Routes &amp; Shelters:<\\/strong><\\/span><br /><a href='http://www.floridadisaster.org/County_EM/county_list.htm'>http://www.floridadisaster.org/County_EM/county_list.htm<\\/a><\\/span><\\/p><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>We&rsquo;ll do our best to keep you updated in the event of any power outages,"
 + " water advisories,"
 + " evacuation orders,"
 + " etc.,"
 + " but please make sure you&rsquo;re tuning into weather and news reports as well. We will be as available as possible before and after the storm,"
 + " but please note that for our team members&rsquo; safety,"
 + " we will also need to follow evacuation orders and the instructions above.<\\/span><br /><br /><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>We cannot respond to emergencies during the storm or in the event of unsafe circumstances<\\/strong>. In the event of an emergency,"
 + " <\\/span><span style='color: rgb(255,"
 + " 0,"
 + " 0);'><strong>please call 911<\\/strong><\\/span>. <span style='color: rgb(105,"
 + " 105,"
 + " 105);'>They <strong>will dispatch personnel as they are able<\\/strong>,"
 + " depending on conditions (winds less than a tropical force of 45 mph).<\\/span><br /><br /><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>After the storm,"
 + " if our phone lines are down,"
 + " you can still email us at naveenreddy4468@gmail.com or call our Service Hotline at 123-4567-890.<\\/span><br /><br /><span style='color: rgb(0,"
 + " 133,"
 + " 202);'><strong>IMPORTANT ADVICE<\\/strong><\\/span><\\/span><\\/p><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>Preparing for a Hurricane<\\/strong><\\/span><\\/span><\\/p><ul><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Check local forecasts on the TV,"
 + " radio,"
 + " and the internet often and know what these terms mean:<\\/span><\\/span><ul><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>Hurricane Watch<\\/strong>: Conditions are possible &ndash; time to start preparing your home and getting your evacuation plan in order in case a warning is issued.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>Hurricane Warning<\\/strong>: Conditions are expected &ndash; time to complete all hurricane preparations and evacuate the area <u>if instructed<\\/u> by local authorities.<\\/span><\\/span><\\/li><\\/ul><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Have an evacuation/family emergency plan ready to go,"
 + " and let your contacts know your plan/location.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Keep a disaster supply/evacuation kit handy,"
 + " and make sure it&rsquo;s equipped to last 3-5 days.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Make sure your <strong>car&rsquo;s gas tank is full<\\/strong> in case you need to evacuate the area.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Make sure <strong>all cell phones and devices are fully charged<\\/strong>,"
 + " and consider getting a back-up charging solution.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Fill up your bathtubs and any large containers you have with water in case of water contamination.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Bring inside or tie down any outside decorations,"
 + " furniture,"
 + " etc.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Keep towels within reach so you can place them in window sills and exterior doorways.<\\/span><\\/span><\\/li><\\/ul><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>During a Hurricane<\\/strong><\\/span><\\/span><\\/p><ul><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>If you remain in the community,"
 + " stay indoors &ndash; away from windows and glass doors. Move to a small interior space like a closet,"
 + " bathroom,"
 + " or hallway.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>In the event of a mandatory evacuation,"
 + " follow instructions from local officials<\\/strong>. Law enforcement and/or the National Guard will be dispatched to knock on doors and help get people out as they are able. If it is safe to do so,"
 + " we will help knock on doors as well.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Shut all interior doors,"
 + " secure or brace exterior doors,"
 + " and keep curtains and blinds completely closed.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>If the power goes out,"
 + " only use battery-powered flashlights. Don&rsquo;t light any candles &mdash; they&rsquo;re potentially hazardous if there is a gas leak.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Resist the temptation to use a personal generator &ndash; for your safety,"
 + " we don&rsquo;t allow them in residents&rsquo; homes or anywhere in the community.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Don&rsquo;t be fooled by a lull in the storm &ndash; it could just be the eye of the storm,"
 + " and winds could come back even stronger.<\\/span><\\/span><\\/li><\\/ul><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>After a Hurricane<\\/strong><\\/span><\\/span><\\/p><ul><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Watch out for possible flooding or tornadoes.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>If you venture out,"
 + " try to stay out of floodwaters,"
 + " and keep away from downed power lines.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>If you evacuated the area,"
 + " don&rsquo;t return until authorities say it&rsquo;s okay to do so.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>If our local waste removal service can&rsquo;t empty the trash,"
 + " use temporary trash containers around the community to avoid pollution or water contamination.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Once the coast is clear,"
 + " our service team will check outbuildings for damage and carry out post-disaster inspections.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Take pictures of damaged property for your insurance purposes.<\\/span><\\/span><\\/li><\\/ul><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><strong>In the Event of Flooding<\\/strong><\\/span><\\/span><\\/p><ul><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Avoid walking,"
 + " standing,"
 + " or driving through floodwaters. Just six inches of moving water can knock a person down,"
 + " and one to two feet of water can move a vehicle.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Move to higher ground as quickly as possible.<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>If you are in your car and water is rising around your car:<\\/span><\\/span><ul><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>if the water is not moving,"
 + " abandon the car and move to higher ground,"
 + " OR<\\/span><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>if the water is moving,"
 + " stay in the car and do not enter moving water.<\\/span><\\/span><\\/li><\\/ul><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>Watch out for debris and areas that may have eroded due to flooding.<\\/span><\\/span><\\/li><\\/ul><p style='text-align: left;'><span style='font-size: 14px;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'>For more general information on storm safety,"
 + " check out the following resources:<\\/span><\\/span><\\/p><ul><li style='text-align: left;'><span style='font-size: 14px;'><a href='http://www.nws.noaa.gov/om/hurricane/plan.shtml'>http://www.nws.noaa.gov/om/hurricane/plan.shtml<\\/a><\\/span><\\/li><li style='text-align: left;'><span style='font-size: 14px;'><\\/ul><p style='text-align: left;'><span style='color: rgb(105,"
 + " 105,"
 + " 105);'><span style='font-size: 14px;'>We know the uncertainty can be difficult,"
 + " but we thank you for your flexibility and patience as we weather the storm with you!<br /><br />Take care and stay safe!<br /><br />Your Team at Devrabbit Apartments<\\/span><\\/span><\\/p><\\/td><\\/tr><tr><td style='text-align: center;'><strong>DEVRABBIT APARTMENTS<\\/strong><br /><strong>354 Sierra Street<\\/strong><br /><strong>San Francisco,"
 + " CA 94551<\\/strong><\\/td><\\/tbody><\\/table>\\\"\\n}\","
 + "\"raw_id\":1398,"
 + "\"dataset_id\":1673,"
 + "\"raw_type_id\":3}";

}